# Generated by Django 3.2.6 on 2021-10-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='percentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.CharField(choices=[('20', '20'), ('40', '40'), ('60', '60'), ('80', '80'), ('100', '100')], default='20', max_length=3)),
            ],
        ),
    ]
